name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Databricks"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        # AQUI ESTÁ A CORREÇÃO FINAL: Usar a ramificação principal (main) para ter as chaves mais recentes
        uses: databricks/setup-cli@main

      - name: Validate Bundle
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy to Production
        run: databricks bundle deploy -t production
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}